exclusive/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('web.urls'))
]               


if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

web/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('',views.index, name='index'),
    path('product',views.view_products, name='view_products'),
    path('productlist', views.products_list, name='product_list'),
    path('subscribe', views.subscribe, name='subscribe'),
    path('product/<int:id>/', views.product, name='product' ),
    path('add-product-page',views.add_product_page,name='add-product-page'),
    path('add_product',views.add_product,name='add_product')
]

web/models.py
from django.db import models
from datetime import datetime
from django.core.validators import MaxValueValidator, MinValueValidator


PRODUCT_CATOGERY = (
    ("phone",'phone'),
    ("computer",'computer'),
    ("smart_watch",'smart watch'),
    ("headphone",'headphone'),
    ("gaming",'gaming'),
    ("camera",'camera'),
)

# PRODUCT_COLOR = (

# )


class Subscribe(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email


class Product(models.Model):
    product_name = models.CharField(max_length=255)
    price = models.IntegerField()
    product_category = models.CharField(max_length=255, choices=PRODUCT_CATOGERY)
    discription = models.TextField()
    date = models.DateField(default=datetime.now)
    discount = models.PositiveIntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])
    rating = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(5)])
    no_of_people_rated = models.PositiveIntegerField()
    product_image = models.ImageField(upload_to='products/')

    def __str__(self):
        return self.product_name


class Spotlight(models.Model):
    logo = models.ImageField(upload_to='spotlight/')
    product_name = models.CharField(max_length=50)
    offer = models.CharField(max_length=255)
    image = models.ImageField(upload_to='spotlight/')

    def __str__(self):
        return self.product_name

web/views.py
import json

from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http.response import HttpResponse
from datetime import date

from web.models import Subscribe, Product, Spotlight
from web.form import ProductForm


def index(request):
    spotlight = Spotlight.objects.last()
    products = Product.objects.all()
    today = date.today()
    products_len = len(products) - 9

    phone_category = Product.objects.filter(product_category='phone')
    computer_category = Product.objects.filter(product_category='computer')
    smartwatch_category = Product.objects.filter(product_category='smart_watch')
    headphone_category = Product.objects.filter(product_category='headphone')
    games_category = Product.objects.filter(product_category='gaming')
    camera_category = Product.objects.filter(product_category='camera')

    context = {
        "products":products[:products_len:-1],
        "today":today,
        "phone_category":phone_category[:8:-1],
        "computer_category":computer_category[:8:-1],
        "smartwatch_category":smartwatch_category[:8:-1],
        "headphone_category":headphone_category[:8:-1],
        "games_category":games_category[:8:-1],
        "camera_category":camera_category[:8:-1],
        "spotlight":spotlight
    }

    return render(request, 'home.html', context=context)


def view_products(request):
    return render(request, 'product-detail.html')


def product(request, id):
    instance = get_object_or_404(Product.objects.filter(id=id))
    usercatogary = instance.product_category
    category = Product.objects.filter(product_category=usercatogary)
    category_len = len(category) - 5

    context = {
        "instance":instance,
        "category_lists" : category[:category_len:-1],
        # "star_count":star_count
    }

    return render(request,'product-detail.html', context=context)


def products_list(request):
    products = Product.objects.all()
    today = date.today()
    products_len = len(products) - 21

    context = {
        "products":products[:products_len:-1],
        "today":today
    }
    
    return render(request, 'product-list.html', context=context)


def add_product_page(request):
    if request.method == 'POST':
        pass
    else:
        form = ProductForm()
        context = {
            "form":form
        }

    return render(request,'add-product.html', context=context)


def subscribe(request):
    email = request.POST.get('email')
    
    if not Subscribe.objects.filter(email=email).exists():
        Subscribe.objects.create(
            email=email
        )

        response_data = {
            'status':"success",
            'title':"Successfully registered",
            "message":"You subscribed to out newsletter successfully"
        }
        
    else:
        response_data = {
            'status':"error",
            'title':"You are already subscribed",
            "message":"You already a memeber, No need to register again"
        }

    return HttpResponse(json.dumps(response_data),content_type="applicatoin/javascript")


#function
def add_product(request): 
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # return redirect('index')

            response_data = {
            'status':"success",
            'title':"Successfully product added",
            "message":"Your product is now added successfully"
            }

            return HttpResponse(json.dumps(response_data),content_type="applicatoin/javascript")
        else:
            response_data = {
            'status':"error",
            'title':"Your product is not added, some field get an error",
            "message":"check discount or rating"
            }

            return HttpResponse(json.dumps(response_data),content_type="applicatoin/javascript")

templates/add-product.html
{% extends './base.html' %}
{% block content %}
{% load static %}
    <section id="location">
        <div class="wrapper">
            <div class="location-div">
                <div>
                    <p>home</p>
                     <p>/</p>
                     <span>add products</span>
                </div>
            </div>
        </div>
    </section>
    <section id="add-product">
        <div class="wrapper">
            <div class="add-product-div">
                <div class="heading">
                    <h3>add product</h3>
                </div>
                <form action="{% url 'web:add_product' %}" method="post" class="ajax">
                    {% csrf_token %}
                    <div class="input-div">
                        <label for="{{form.product_name.id_for_label}}">{{form.product_name.label}}</label>
                        {{form.product_name}}
                    </div>
                    <div class="input-div">
                        <label for="{{form.price.id_for_label}}">{{form.price.label}}</label>
                        {{form.price}}
                    </div>
                    <div class="input-div">
                        <label for="{{form.product_category.id_for_label}}">{{form.product_category.label}}</label>
                        {{form.product_category}}
                    </div>
                    <div class="input-div">
                        <label for="{{form.discription.id_for_label}}">{{form.discription.label}}</label>
                        {{form.discription}}
                    </div>
                    <div class="input-div">
                        <label for="{{form.date.id_for_label}}">{{form.date.label}}</label>
                        {{form.date}}
                    </div>
                    <div class="input-div">
                        <label for="{{form.discount.id_for_label}}">{{form.discount.label}}  (0-100)</label>
                        {{form.discount}}
                    </div>
                    <div class="input-div">
                        <label for="{{form.rating.id_for_label}}">{{form.rating.label}} (0 - 5)</label>
                        {{form.rating}}
                    </div>
                    <div class="input-div">
                        <label for="{{form.no_of_people_rated.id_for_label}}">{{form.no_of_people_rated.label}}</label>
                        {{form.no_of_people_rated}}
                    </div>
                    <div class="input-div">
                        <label for="{{form.product_image.id_for_label}}">{{form.product_image.label}}</label>
                        {{form.product_image}}
                    </div>
                    <div class="input-div submit-btn">
                        <input type="submit" value="Add product">
                    </div>
                </form>
                <div class="input-div submit-btn">
                    <a href="{% url 'web:index' %}">
                        <button>back to home</button>
                    </a>
                </div>
            </div>
        </div>
    </section>

    {% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
<body>
    <section class="offer">
        <div class="wrapper">
            <div class="offer-div">
                <p class="summerSale">summer sale for all swim suits and free express delivery - OFF 50%! <a href="">ShopNow</a></p>
                <div class="langauge">
                    <select name="" id="">
                        <option value="English">English</option>
                        <option value="Hindi">Hindi</option>
                    </select>
                </div>
            </div>
        </div>
    </section>
    <header>
        <div class="wrapper">
            <div class="header-div">
                <div class="hamburger" onclick="myFunction()">
                    <i class="fa fa-bars"></i>
                </div>
                <h1>
                    <a href="#">
                        <img src="{% static './images/Logo.png' %}" alt="">
                    </a>
                </h1>
                <nav id="navbar">
                    <a href="{% url 'web:index' %}">home</a>
                    <a href="{% url 'web:view_products' %}">Contact</a>
                    <a href="{% url 'web:product_list' %}">About</a>
                    <a href="">Sign up</a>
                    <a href="{% url 'web:add-product-page' %}">Add product</a>
                </nav>
                <div class="right_nav">
                    <div class="searchDiv">
                        <input type="text" placeholder="What are you looking for?">
                        <i class="fa fa-search"></i>
                    </div>
                    <div class="search-icon">
                        <i class="fa fa-search"></i>
                    </div>
                    <div>
                        <i class="fa fa-heart-o"></i>
                    </div>
                    <div>
                        <i class="fa fa-shopping-cart"></i>
                    </div>
                </div>
            </div>
        </div>
    </header>

    {% block content %}

    {% endblock %}

    <footer>
        <div class="wrapper">

            <div class="footer-main">
                <div class="column-container">
                    <h5>exclusive</h5>
                    <h6>Subscribe</h6>
                    <p>Get 10% off your first order</p>
                    <div class="newsletter-input">
                        <form action="{% url 'web:subscribe' %}" method="POST" class="ajax">
                            {% csrf_token %}
                            <input type="email" placeholder="enter your email" name="email">
                            <button type="submit"><svg width="30" height="30" viewBox="0 0 24 24" fill="#000000" xmlns="http://www.w3.org/2000/svg">
                                <path d="M9.91196 12H3.99996L2.02296 4.13499C2.0103 4.08928 2.00259 4.04234 1.99996 3.99499C1.97796 3.27399 2.77196 2.77399 3.45996 3.10399L22 12L3.45996 20.896C2.77996 21.223 1.99596 20.737 1.99996 20.029C2.00198 19.9657 2.0131 19.9031 2.03296 19.843L3.49996 15" stroke="#FAFAFA" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                                </svg>
                            </button>
                            <!-- <button type="submit"><img src="{% static 'images/icon-send.png' %}" alt="sent-icon"></button> -->
                        </form>
                    </div>
                </div>
                <div class="column-container">
                    <h6>support</h6>
                    <p>111 Bijoy sarani, Dhaka,  DH 1515, Bangladesh.</p>
                    <p>exclusive@gmail.com</p>
                    <p>+88015-88888-9999</p>
                </div>
                <div class="column-container">
                    <h6>account</h6>
                    <a href=""><p>my account</p></a>
                    <a href=""><p>login / register</p></a>
                    <a href=""><p>categories</p></a>
                    <a href=""><p>wishlist</p></a>
                    <a href=""><p>shop</p></a>
                </div>
                <div class="column-container">
                    <h6>quick link</h6>
                    <a href=""><p>privacy policy</p></a>
                    <a href=""><p>terms of use</p></a>
                    <a href=""><p>faq</p></a>
                    <a href=""><p>contact</p></a>
            </div>
            <div class="column-container">
                <h6>download app</h6>
                <div class="qr-code">
                    <p>Save $3 with App New User Only</p>
                    <div class="center">
                        <div class="qr-image">
                            <img src="{% static 'images/Qrcode.jpg' %}" alt="qrCode">
                        </div>
                        <div class="download-platform">
                            <div class="downloaded-by">
                                <img src="{% static 'images/download-appstore.jpg' %}" alt="appStore">
                            </div>
                            <div class="downloaded-by">
                                <img src="{% static 'images/download-playstore.jpg' %}" alt="playstore">
                            </div>
                        </div>
                    </div>
                    <div class="social-media">
                        <a href=""><div class="each">
                            <img src="{% static 'images/icon-instagram.png' %}" alt="social-media-icon">
                        </div></a>
                        <a href=""><div class="each">
                            <img src="{% static 'images/Icon-Facebook.png' %}" alt="social-media-icon">
                        </div></a>
                        <a href=""><div class="each">
                            <img src="{% static 'images/Icon-Twitter.png' %}" alt="social-media-icon">
                        </div></a>
                        <a href=""><div class="each">
                            <img src="{% static 'images/Icon-Linkedin.png' %}" alt="social-media-icon">
                        </div></a>
                    </div>
                </div>
            </div> 
        </div>
    </div>
    <div class="copyright">
        <p>Copyright Rimel 2022. All right reserved</p>
    </div>
    </footer>
    
</body>
<script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
<script src="{% static 'js/sweetalert2.min.js' %}"></script>
</html>

templates/product-detail.html
{% extends './base.html' %}
{% block content %}
{% load static %}
 
    <section id="location">
        <div class="wrapper">
            <div class="location-div">
                <div>
                    <p>home</p>
                    <p>/</p>
                    <p>{{instance.product_category}}</p>
                    <p>/</p>
                    <span>{{instance.product_name}}</span>
                </div>
            </div>
        </div>
    </section>
    <section id="single">
        <div class="wrapper">
            <div class="single-div">
                <div class="left">
                    <div class="single-image">
                        <img src="{{instance.product_image.url}}" alt="Item-image">
                    </div>
                </div>
                <div class="right">
                    <div class="top">
                        <h5>{{instance.product_name}}</h5>
                        <div class="rating">
                            <div class="stars">
                                {% if instance.rating > 4  %}
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                    {% elif instance.rating > 3  %}
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                    {% elif instance.rating > 2  %}
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                    {% elif instance.rating > 1  %}
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                    {% elif instance.rating > 0  %}
                                        <i class="fa fa-star-"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                    {%  endif %}
                            </div>
                            <p>({{instance.no_of_people_rated}} reviews)</p>
                            <p>|</p>
                            <span>in stock</span>
                        </div>
                        <p class="price">${{instance.price}}.00</p>
                        <p class="details">{{instance.discription}}</p>
                    </div>
                    <div class="bottom">
                        <div class="colors">
                            <p>colours:</p>
                            <div class="color">
                                <div class="clr1"></div>
                                <div class="clr2"></div>
                            </div>
                        </div>
                        <div class="features">
                            <div class="feature">
                                <div class="image">
                                    <img src="{% static 'images/services-delivery.png' %}" class="image-1" alt="delivery-icon">
                                </div>
                                <div>
                                    <p class="head">Free Delivery</p>
                                    <p class="content">Enter your postal code for Delivery Availability</p>
                                </div>
                            </div>
                            <div class="feature">
                                <div class="image">
                                    <img src="{% static 'images/Icon-return.png' %}" alt="return-icon">
                                </div>
                                <div>
                                    <p class="head">Return Delivery</p>
                                    <p class="content">Free 30 Days Delivery Returns. Details</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section id="products">
        <div class="wrapper">
            <div class="products-div">
                <div class="tophead">
                    <div></div>
                    <h3>Categories</h3>
                </div>
                <div class="items active">
                    {% for category_list in category_lists %}
                    <div class="item">
                        <a href="{% url 'web:product' id=category_list.id %}">

                            <div class="item-image">
                                <div class="topsection">
                                    <div class="image">
                                        <img src="{{category_list.product_image.url}}" alt="item-image">
                                    </div>
                                </div>
                                <div class="item-icons">
                                    
                                    <div class="item-i  con">
                                    <i class="fa fa-heart-o"></i>
                                </div>
                                <div class="item-icon">
                                    <i class="fa fa-eye"></i>
                                </div>
                            </div>
                            <div class="addCart">
                                <p>Add to cart</p>
                            </div>
                        </div>
                        <div class="item-main">
                            <p class="item-head">{{category_list.product_name}}</p>
                            <div class="bottom-part">
                                <p class="price">$100</p>
                                <div>
                                    {% if category_list.rating > 4  %}
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                    {% elif category_list.rating > 3  %}
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                    {% elif category_list.rating > 2  %}
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                    {% elif category_list.rating > 1  %}
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                    {% elif category_list.rating > 0  %}
                                        <i class="fa fa-star-"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                        <i class="fa fa-star-o"></i>
                                    {%  endif %}
                                
                                </div>
                                <p class="review">(23)</p>
                            </div>
                        </div>
                        <div class="item-bottom">
                            <div class="color">
                                <div></div>
                                <div></div>
                            </div>
                        </div>
                    </a>
                    </div>
                    {% endfor %}
                    
                </div>
            </div>
        </div>
    </section>
  {% endblock %}